//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImage
    {
        public int imgId { get; set; }
        public string imgLabel { get; set; }
        public string imgDescription { get; set; }
        public string imgFileName { get; set; }
        public string imgContentType { get; set; }
        public int imgWidth { get; set; }
        public int imgHeight { get; set; }
        public System.DateTime imgCreationDate { get; set; }
        public bool imgIsInActive { get; set; }
    }
}
