//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubject
    {
        public int sjId { get; set; }
        public string sjBSN { get; set; }
        public string sjGender { get; set; }
        public Nullable<System.DateTime> sjDateOfBirth { get; set; }
        public Nullable<System.DateTime> sjDateOfDeath { get; set; }
        public Nullable<int> sjMaritalStatusId { get; set; }
        public bool sjIsInactive { get; set; }
        public Nullable<System.DateTime> sjAnonymisedOn { get; set; }
        public string sjWoonplaatsSource { get; set; }
        public Nullable<int> sjWoonplaatsId { get; set; }
    }
}
